'use client'
import AppShell from '@/components/AppShell'
import { useEffect, useState } from 'react'
import { getCurrentUserProfile } from '@/lib/auth'
import { getMyProcedures } from '@/lib/procedures'
import type { Procedimiento, Usuario } from '@/types/database'

export default function HistorialPage(){
 const [user,setUser]=useState<Usuario|null>(null); const [items,setItems]=useState<Procedimiento[]>([]); const [msg,setMsg]=useState('')
 useEffect(()=>{async function load(){try{const u=await getCurrentUserProfile(); setUser(u); if(u) setItems(await getMyProcedures(u.id) as Procedimiento[])}catch{setMsg('Configura Supabase e inicia sesión para ver historial real.')}} load()},[])
 return <AppShell><section className="rounded-[2rem] border border-white/10 bg-white/[0.04] p-5"><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-3xl bg-cyan-400/20 text-2xl font-bold text-cyan-200">{user?`${user.nombre[0]}${user.apellido[0]}`:'BK'}</div><div><h2 className="text-2xl font-bold">{user?`${user.nombre} ${user.apellido}`:'Historial individual'}</h2><p className="text-sm text-white/50">Becado/a Medicina de Urgencia</p></div></div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><div className="rounded-2xl bg-white/5 p-3"><b className="block text-2xl">{items.length}</b><span className="text-xs text-white/50">Total</span></div><div className="rounded-2xl bg-white/5 p-3"><b className="block text-2xl text-emerald-300">{items.filter(i=>i.exitoso).length}</b><span className="text-xs text-white/50">Éxito</span></div><div className="rounded-2xl bg-white/5 p-3"><b className="block text-2xl text-amber-300">{items.filter(i=>i.estado_validacion==='pendiente').length}</b><span className="text-xs text-white/50">Pend.</span></div></div></section>{msg&&<p className="mt-4 rounded-2xl bg-white/10 p-3 text-sm text-white/70">{msg}</p>}<section className="mt-5"><h3 className="mb-3 text-lg font-bold">Historial</h3>{items.length===0&&!msg&&<p className="rounded-3xl border border-white/10 bg-white/5 p-5 text-white/70">Sin procedimientos aún.</p>}{items.map(p=><div key={p.id} className="mb-3 rounded-3xl border border-white/10 bg-white/[0.04] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{p.procedimiento}</p><p className="mt-1 text-sm text-white/50">Estado: {p.estado_validacion}</p><p className="mt-2 text-xs text-white/35">{new Date(p.fecha_hora_registro).toLocaleString('es-CL')}</p></div><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs text-emerald-300">{p.exitoso?'Exitoso':'No exitoso'}</span></div></div>)}</section></AppShell>
}
