'use client'
import AppShell from '@/components/AppShell'
import { useEffect, useState } from 'react'
import { getDashboardBecados, getProceduresByType } from '@/lib/dashboard'

type AnyRow = Record<string, any>
export default function DashboardPage(){
 const [becados,setBecados]=useState<AnyRow[]>([]); const [tipos,setTipos]=useState<AnyRow[]>([]); const [msg,setMsg]=useState('')
 useEffect(()=>{async function load(){try{setBecados(await getDashboardBecados()); setTipos(await getProceduresByType())}catch{setMsg('Configura Supabase e inicia sesión como docente para ver dashboard real.')}} load()},[])
 const total=becados.reduce((a,b)=>a+Number(b.total_procedimientos||0),0); const pend=becados.reduce((a,b)=>a+Number(b.pendientes||0),0); const val=becados.reduce((a,b)=>a+Number(b.procedimientos_validados||0),0)
 return <AppShell><div className="mb-5"><h2 className="text-2xl font-bold">Dashboard docente</h2><p className="text-sm text-white/50">Seguimiento global del programa.</p></div>{msg&&<p className="mb-4 rounded-2xl bg-white/10 p-3 text-sm text-white/70">{msg}</p>}<div className="grid grid-cols-3 gap-2"><Stat label="Total" value={total}/><Stat label="Validados" value={val}/><Stat label="Pendientes" value={pend}/></div><section className="mt-5 rounded-3xl border border-white/10 bg-white/[0.04] p-5"><h3 className="mb-4 font-bold">Procedimientos por tipo</h3>{tipos.length===0&&<p className="text-sm text-white/50">Sin datos aún.</p>}{tipos.map(t=><div key={t.procedimiento} className="mb-3"><div className="flex justify-between text-sm"><span className="text-white/70">{t.procedimiento}</span><span>{t.total}</span></div><div className="mt-1 h-3 rounded-full bg-white/10"><div className="h-3 rounded-full bg-cyan-400" style={{width:`${Math.min(100,Number(t.total)*10)}%`}}/></div></div>)}</section><section className="mt-5 rounded-3xl border border-white/10 bg-white/[0.04] p-5"><h3 className="mb-4 font-bold">Becados</h3>{becados.length===0&&<p className="text-sm text-white/50">Sin datos aún.</p>}{becados.map(b=><div key={b.becado_id} className="mb-3 rounded-3xl border border-white/10 bg-black/20 p-4"><div className="mb-2 flex justify-between"><p className="font-semibold">{b.nombre} {b.apellido}</p><p className="text-sm text-emerald-300">{b.tasa_exito}% éxito</p></div><div className="grid grid-cols-3 gap-2 text-center text-xs text-white/60"><div className="rounded-2xl bg-white/5 p-2"><b className="block text-lg text-white">{b.total_procedimientos}</b>Total</div><div className="rounded-2xl bg-white/5 p-2"><b className="block text-lg text-white">{b.exitosos}</b>Exitosos</div><div className="rounded-2xl bg-white/5 p-2"><b className="block text-lg text-white">{b.pendientes}</b>Pend.</div></div></div>)}</section></AppShell>
}
function Stat({label,value}:{label:string,value:number}){return <div className="rounded-3xl border border-cyan-400/20 bg-cyan-400/10 p-4"><p className="text-xs text-white/60">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>}
